Elisab.WebApp/Controllers/FashionShowController.cs
using Elisab.BAL.Repository;
using System.Web.Mvc;

namespace Elisab.Controllers
{
  public class FashionShowController : BaseController
  {
    FashionShowsRepository _fashionShowsRepository;

    public ActionResult List()
    {
      return View();
    }

    public ActionResult Save(int Id = 0)
    {
      _fashionShowsRepository = new FashionShowsRepository();
      return View(_fashionShowsRepository.Get(Id));
    }
  }
}

Elisab.WebApp/Controllers/LandingPageController.cs
using Elisab.BAL.Repository;
using System.Web.Mvc;

namespace Elisab.Controllers
{
  public class LandingPageController : Controller
  {
    FashionShowsRepository _fashionShowsRepository;
    CountDownPageRepository _countDownPageRepository;
    public LandingPageController()
    {
      _fashionShowsRepository = new FashionShowsRepository();
      _countDownPageRepository = new CountDownPageRepository();
    }

    public ActionResult Index(int id = 0)
    {

      var rec = _fashionShowsRepository.GetLandingPage(id);
      if (rec.IsFutureEvent == true)
      {
        return RedirectToAction("CountDown");
      }
      else
      {
        return View(rec);
      }
    }

    public ActionResult CountDown(int id = 0)
    {
      return View(_countDownPageRepository.GetPreview(id));
    }
  }
}

Elisab.WebApp/Views/FashionShow/FashionShow_PartialView.cshtml
@model List<Elisab.BAL.ViewModel.FashionShows_VM>
@if (Model != null)
{
  <table class="table table-bordered" id="fashionShowTable">
    <thead>
      <tr>
        <th class="w-50">Name</th>
        <th class="w-10 text-center">Show Date Time</th>
        <th class="no-sort w-10 text-center">Count Down Preview</th>
        <th class="no-sort text-center w-10">Active</th>
        <th class="no-sort text-center w-10">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
        <tr>
          <td><a target="_blank" href="/GalleryLogin/Index/@Elisab.WebApp.Helper.Helper.EncodeServerName(item.Id.ToString())">@item.Name</a></td>
          <td class="text-right">@item.ShowDate  @item.ShowTime</td>
          <td class="text-center">
            <a target="_blank" href="@Url.Action("CountDown", "LandingPage", new { Id = item.Id })">
              Click
            </a>
          </td>
          <td class="text-center">
            @Html.CheckBoxFor(x => item.IsActive, new { id = item.Id, onchange = "onActiveChange('" + item.Id + "')" })
          </td>
          <td class="text-center">
            <a href="@Url.Action("Save", "FashionShow", new { Id = item.Id })" class="mr-10">
              <i class="fa fa-edit" aria-hidden="true"></i>
            </a>
            <a href="javascript:if (confirm('Are you sure you want to delete this fashion show ?')) { Delete('@item.Id') }" class="mr-10">
              <i class="fa fa-trash" aria-hidden="true"></i>
            </a>

            <a target="_blank" href="@Url.Action("Index", "LandingPage", new { Id = item.Id })">
              <i class="fa fa-eye" aria-hidden="true"></i>
            </a>

          </td>
        </tr>
      }
    </tbody>
  </table>
}


<script>
  $(document).ready(function () {
    $('#fashionShowTable').DataTable({
      "columnDefs": [{
        "targets": 'no-sort',
        "orderable": false,
      }]
    });
  });
</script>

Elisab.WebApp/Views/FashionShow/List.cshtml
@model List<Elisab.BAL.ViewModel.FashionShows_VM>
@{
  ViewBag.Title = "Fashion Shows";
}

<section class="content-header">
  <h1>
    @ViewBag.Title
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="@Url.Action("Index", "Home")">
        <i class="fa fa-home"></i> Home
      </a>
    </li>
    <li class="active">
      <a href="@Url.Action("List", "FashionShow")">
        @ViewBag.Title
      </a>
    </li>
  </ol>
</section>

<div class="clear">
  <div class="box box-primary clear">
    <div class="box-body">
      <div class="row">
        <div class="col-xs-12 text-right mb-15">
          <a class="btn btn-primary" href="@Url.Action("Save", "FashionShow")">Add New</a>
        </div>
      </div>
      <div id="fashionShowList">

      </div>

    </div>
  </div>
</div>
<script src="~/Script/common.js"></script>
<script src="~/Content/js/plugins/jquery/jquery-3.3.1.min.js"></script>
<script src="~/Script/FashionShow.js?@Elisab.WebApp.Helper.Helper.UnqiueId()"></script>
<script>
  GetAll();
</script>

Elisab.WebApp/Views/FashionShow/Save.cshtml
@model Elisab.BAL.ViewModel.FashionShows_VM
@{
  ViewBag.Title = "Fashion Shows";
}


<section class="content-header">
  <h1>
    @ViewBag.Title
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="@Url.Action("Index", "Home")">
        <i class="fa fa-home"></i> Home
      </a>
    </li>
    <li class="active">
      <a href="@Url.Action("List", "FashionShow")">
        @ViewBag.Title
      </a>
    </li>
    <li class="active">
      @if (Model != null && Model.Id > 0)
      {
        <a href="@Url.Action("Save", "FashionShow")">
          Fashion Show Edit
        </a>
      }
      else
      {
        <a href="@Url.Action("Save", "FashionShow")">
          Fashion Show Add
        </a>
      }
    </li>
  </ol>
</section>

<div class="box box-primary clear">
  <form role="form">
    <div class="box-body">
      <div class="row">
        @Html.HiddenFor(m => m.Id)

        <div class="form-group col-xs-4">
          <label>Name<span class="require">*</span></label>
          @Html.TextBoxFor(m => m.Name, new { placeholder = "Name", @class = "form-control" })
        </div>

        <div class="form-group col-xs-4">
          <label>Show Date<span class="require">*</span></label>
          <div class="input-group date">
            <div class="input-group-addon" id="showDateDiv">
              <i class="fa fa-calendar"></i>
            </div>
            @Html.TextBoxFor(m => m.ShowDate, new { placeholder = "Show Date", @class = "form-control pull-right datepicker", autocomplete = "off" })
          </div>
        </div>

        <div class="form-group col-xs-2">
          <label>Show Time<span class="require">*</span></label>
          <div class="input-group">
            @Html.TextBoxFor(m => m.ShowTime, new { placeholder = "Show Time", @class = "form-control pull-right timepicker", autocomplete = "off" })
          </div>
        </div>

        <div class="form-group col-xs-2">
          <label>Is Active<span class="require">*</span></label>
          <div class="input-group">
            @Html.CheckBoxFor(m => m.IsActive)
          </div>
        </div>

      </div>
    </div>

    <div class="box-footer">
      <button type="button" class="btn btn-primary" style="margin-right:5px" onclick="Add()">Submit</button>
      <button type="button" class="btn btn-default" onclick="goBack()">Back</button>
    </div>
  </form>
</div>


<script src="~/Script/FashionShow.js?@Elisab.WebApp.Helper.Helper.UnqiueId()"></script>